name: Auto Assign

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    uses: paulofponciano-idp/.github/.github/workflows/auto-assign.yaml@main
    secrets: inherit
    with:
      assignees: paulofponciano
      numOfAssignee: 1