name: First Release

on:
  workflow_dispatch:

jobs:
  env:
    uses: paulofponciano-idp/.github/.github/workflows/env.yaml@main

  deploy:
    uses: paulofponciano-idp/.github/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      tag: ${{ needs.env.outputs.tag }}
      repository: ${{ needs.env.outputs.repository }}
      url: https://${{ needs.env.outputs.repository }}.pauloponciano.digital
      environment: production
    needs:
      - env